sudo: required
language: python
python: "2.7_with_system_site_packages"
env: "OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0"
before_install:
    - bash -ex config/ocaml_install.sh
install: true
script: make test
